version: "3.9"

services:

  mysql:
      image: mysql:latest
      container_name: mysql
      volumes:
        - mysql-keycloak:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root_pwd
        MYSQL_DATABASE: keycloak
        MYSQL_USER: admin
        MYSQL_PASSWORD: pa55word
      ports:
        - 3306:3306
      networks:
        - kazum

  keycloak:
      image: quay.io/keycloak/keycloak:19.0.1
      container_name: keycloack
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_DB: mysql
        KC_DB_USERNAME: admin
        KC_DB_PASSWORD: pa55word
        KC_DB_URL_HOST: mysql
        KC_DB_URL_PORT: 3306
        KC_DB_SCHEMA: keycloak
      ports:
        - 8080:8080
      depends_on:
        - mysql
      command: start-dev
      networks:
        - kazum


volumes:
  mysql-keycloak:

networks:
  kazum:
    name: kazum-network